SET NAMES UTF8;
DROP DATABASE IF EXISTS coffee;
CREATE DATABASE coffee CHARSET=UTF8;
USE coffee;
CREATE TABLE users(
	uid INT PRIMARY KEY AUTO_INCREMENT,
	uphone VARCHAR(24),
	upwd  VARCHAR(12),
	ucid  VARCHAR(12)
);